//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GD64.rc
//
#define IDC_MYICON                      2
#define IDD_GD64_DIALOG                 102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDS_VERSION                     104
#define IDM_EXIT                        105
#define IDI_GD64                        107
#define IDI_SMALL                       108
#define IDC_GD64                        109
#define IDR_MAINFRAME                   128
#define IDD_FILEVIEW                    129
#define IDD_VIEWER3D                    130
#define ID_VIEW_TOPVIEW                 131
#define ID_VIEW_SIDEVIEW                132
#define ID_VIEW_FRONTVIEW               133
#define IDD_PREFERENCES                 134
#define IDD_TOPBAR                      135
#define IDD_TB_TAB                      136
#define IDB_GRIDON                      138
#define IDD_TB_CAMERA                   138
#define IDB_GRIDOFF                     139
#define IDD_TB_CAMERA1                  139
#define IDB_HAIRON                      140
#define IDB_HAIROFF                     141
#define IDD_MESSAGE                     142
#define IDD_RESOURCESMATERIAL           143
#define IDD_IMPORT_OPTIONS              144
#define IDD_PLEASEWAIT                  145
#define IDB_MESHON                      146
#define IDB_MESHOFF                     147
#define IDB_TB_MODELDATAON              148
#define IDB_TB_MODELDATAOFF             149
#define IDB_BONDINGBOXON                150
#define IDB_BONDINGBOXOFF               151
#define IDB_MESHPOINTSON                152
#define IDB_MESHPOINTSOFF               153
#define IDB_BONESON                     154
#define IDB_BONESOFF                    155
#define IDB_NORMALSON                   156
#define IDB_NORMALSOFF                  157
#define IDB_TEXTURESON                  158
#define IDB_TEXTURESOFF                 159
#define IDB_BITMAP1                     160
#define IDB_DUMMY                       160
#define IDD_YESNO                       161
#define IDD_MOUSESENSITIVITY            162
#define IDD_TB_PHYSICS                  163
#define IDD_FPSLOCK                     164
#define IDD_TB_MOTIONS                  165
#define IDD_EXPORT_OGRE_OPTIONS         166
#define IDD_TEXT_DIALOG                 167
#define IDD_TEXTUREVIEWER               168
#define IDD_FILEVIEWER                  169
#define IDD_PROPS_TEXTURES              170
#define IDD_PROPS_TEXTUREVIEWER         171
#define IDB_NO_TEXTURE                  171
#define IDD_LISTSCENE                   172
#define IDB_FILEINACTIVE                173
#define IDB_TREE                        176
#define IDB_FILE                        177
#define IDB_FILESELECTED                178
#define IDB_FILECHANGED                 179
#define IDB_FILECHANGEDSELECTED         180
#define IDB_FVFOLDERRED                 181
#define IDD_PROPERTIES                  182
#define IDD_PROJECTSAVE                 183
#define IDD_TRUEFALSE                   184
#define IDD_TB_GAME                     185
#define IDD_SOUNDPLAYER                 186
#define IDD_PROPS_OBJECT                187
#define IDD_PROPS_COUNTER               188
#define IDD_PROPS_PHYSTEST              189
#define IDC_CK_SU_FULLSCREEN            1000
#define IDC_ST_STARTUP                  1001
#define IDC_CK_SU_FULL3DVIEW            1002
#define IDC_BT_TDH_DEBUG                1002
#define IDC_BT_TD_DEBUG_RESETVIEW       1003
#define IDC_BT_TD_DEBUG_IMGUIDEMO       1004
#define IDC_BT_TD_DEBUG_TESTCUBE        1005
#define IDC_BT_TD_DEBUG_IMGUIFPS        1006
#define IDC_BUTTON1                     1007
#define IDC_BT_APPRESOURCES             1007
#define IDC_BT_TD_DEBUG_TRAYSFPS        1007
#define IDC_BTSHOWTEXTURES              1007
#define IDC_BT_CAMERA_CAMDATA           1007
#define IDC_CKNORMAL                    1007
#define IDC_BT_TD_PHYSICSTAB            1007
#define IDC_BT_TD_DEMOS_OPTIONS         1007
#define IDC_BT_MOTIONS_PLAY             1007
#define IDC_BT_CHANGE_NAME              1007
#define IDC_BT_VIEWEXPORT               1007
#define IDC_BT_LIST_OVERLAY             1007
#define IDC_BT_PT_EXPORT                1007
#define IDC_BT_MAINENVIRONMENT          1007
#define IDC_BT_GAME_PREVIEW             1007
#define IDC_PLAY                        1007
#define IDC_BT_DETAIL                   1007
#define IDC_BT_COUNTER                  1007
#define IDC_BT_TEST_ENTITY              1007
#define IDC_BUTTON2                     1008
#define IDC_BT_TBH_CAMERA               1008
#define IDC_BT_DEMORESOURCES            1008
#define IDC_BTSHOWNORMALS               1008
#define IDC_BT_CAMERA_FIRST             1008
#define IDC_CKSLOW                      1008
#define IDC_BT_TD_DEBUG_FPSLOCK         1008
#define IDC_BT_MOTIONS_STOP             1008
#define IDC_BT_BROWSE                   1008
#define IDC_BUTTON3                     1009
#define IDC_BT_CAMERA_MODEL             1009
#define IDC_ALLMESH                     1009
#define IDC_TBSHOWFACES                 1009
#define IDC_CKFAST                      1009
#define IDC_BT_TD_MOTIONSTAB            1009
#define IDC_BT_MOTIONS_PAUSE            1009
#define IDC_BT_FOLDER_NAME              1009
#define IDC_BT_PT_VIEWMESH              1009
#define IDC_BT_GAME_BUILDGAME           1009
#define IDC_BT_STOP                     1009
#define IDC_BUTTON4                     1010
#define IDC_BT_CAMERA_FREE              1010
#define IDC_ALLMATERIALS                1010
#define IDC_BTSHOWBONES                 1010
#define IDC_CKVERYSLOW                  1010
#define IDC_BT_TD_RESOURCETAB           1010
#define IDC_BT_PT_VIEWMAT               1010
#define IDC_TBSHOWHAIR                  1011
#define IDC_BT_TD_DEBUG_PHYSICSDEBUG    1011
#define IDC_TBSHOWGRID                  1012
#define IDC_BT_TD_DEMOSTAB              1012
#define IDC_BT_TD_DEMOS_DEMO1           1013
#define IDC_BTSHOWPOINTS                1013
#define IDC_BT_TD_DEMOS_DEMO2           1014
#define IDC_TBBOUNDBOX                  1014
#define IDC_BANNER                      1015
#define IDC_BUTTON7                     1015
#define IDC_STTEXT                      1016
#define IDC_TBINFO                      1016
#define IDC_BT_TD_DEBUG_RESOURCES       1017
#define IDC_ST_BANNER                   1018
#define IDC_USEDMATERIALS               1019
#define IDC_ALLTEXTURES                 1020
#define IDC_ST_ABOUT_BANNER             1021
#define IDC_CK_COVERT_TO_OGRE           1022
#define IDC_CK_CREATEPHYSICS            1023
#define IDC_STWAIT                      1023
#define IDC_ST_ABOUT_VERSION            1024
#define IDC_LIST_ABOUT_VERSIONS         1025
#define IDC_STCOUNT                     1026
#define IDC_BANNER_YN                   1027
#define IDC_STTEXT_YN                   1028
#define IDC_BT_CAMERA_SPEED1            1029
#define IDC_STTEXT_YN3                  1029
#define IDC_STBANNER                    1030
#define IDC_CHECK1                      1031
#define IDC_CK_SU_DIRECTORIES           1031
#define IDC_CK_FPSNOLOCK                1031
#define IDC_CK_EXPORT_TO_OGRE           1031
#define IDC_CK_SUBFOLDER                1031
#define IDC_CK_SP_DESKTOP               1031
#define IDC_CHECKYES                    1031
#define IDC_CK_ENABLE                   1031
#define IDC_CB_FPSLIST                  1032
#define IDC_CHECKNO                     1032
#define IDC_ST_FPSSETTINGS              1033
#define IDC_CB_MOTIONS_MOTIONS          1036
#define IDC_ST_MOTIONS_MOTIOINS         1037
#define IDC_CB_MOTIONS_SPEED            1038
#define IDC_ST_MOTIONS_SPEED            1039
#define IDC_ST_FOLDER                   1039
#define IDC_ST_NAME                     1040
#define IDC_ST_SUBFOLDER_NAME           1041
#define IDC_ST_FN                       1042
#define IDC_EDITTEXT                    1043
#define IDC_TITLENAME                   1044
#define IDC_ST_FLD                      1044
#define IDC_CK_EDGE_LIST                1045
#define IDC_CB_RESOURCEGROUPS           1047
#define IDC_BT_RE_SCAN                  1048
#define IDC_ST_RESOURCE_GROUP           1049
#define IDC_ST_GB_LISTOPTIONS           1050
#define IDC_ST_GB_OPTIONS               1051
#define IDC_GROUPALL                    1052
#define IDC_BT_EXPORT                   1053
#define IDC_LST_GROUPS                  1054
#define IDC_BT_VIEWFILE                 1056
#define IDC_BASETEXTURE                 1057
#define IDC_BT_LIST_SKELETON            1058
#define IDC_ST_DETAILS                  1059
#define IDC_ST_SELECTEDFILE             1060
#define IDC_LST_FILE                    1061
#define IDC_PROP_BASETEXTURE            1062
#define IDC_PT_TEXTURENAME              1063
#define IDC_ST_PT_MATERIAL              1064
#define IDC_ST_PT_DIMENSIONS            1065
#define IDC_ST_MATERIAL                 1066
#define IDC_ST_TEXURENAME               1067
#define IDC_STMESSAGE                   1067
#define IDC_ST_PT_MATERIALFILE          1068
#define IDC_ST_PT_NUMTEXTUNITS          1069
#define IDC_TREE1                       1070
#define IDC_STPJFOLDERPATH              1071
#define IDC_BT_TBH_GAME                 1072
#define IDC_BT_GAME_CONFIG              1073
#define IDC_SOUNDLIST                   1074
#define IDC_SLVOLUME                    1075
#define IDC_EDITINT                     1076
#define IDC_BT_PAUSE                    1077
#define IDC_VOLBOX                      1078
#define IDC_STVOLUME                    1079
#define IDC_BT_GOTO                     1080
#define IDC_EDTRIGGERVALUE              1081
#define IDC_STCOUNTERNAME               1082
#define IDC_STMATHS                     1083
#define IDC_BT_CT_MATHS                 1084
#define IDC_ST_CT_COUNTER               1085
#define IDC_ST_CT_MATHS                 1086
#define IDC_STTRIGGERVALUE              1087
#define IDC_BT_PHYSRESET                1088
#define ID_VIEW_RESET                   32771
#define ID_VIEW_MAX3DVIEW               32772
#define ID_DEBUG_TESTPREFERANCE         32773
#define ID_OPTIONS_PREFERENCES          32774
#define ID_FILE_IMPORT                  32775
#define ID_IMPORT_WAVEFRONTOBJ          32776
#define ID_DEBUG_HIDEOGRETESTCUBE       32777
#define ID_DEBUG_IMGUI                  32778
#define ID_IMGUI_IMGUIDEMO              32779
#define ID_CAMERA_MODE                  32780
#define ID_MODE_MODEL                   32781
#define ID_MODE_FREE                    32782
#define ID_DEBUG_CAMERADATA             32783
#define ID_INFO_ASSIMPMODELDATA         32784
#define ID_FILE_CONVERTTOOGRE3D         32785
#define ID_MOUSEANDKEYS                 32786
#define ID_IMPORT_OGRE3D                32787
#define ID_OGRE3D_MESH                  32788
#define ID_OGRE3D_RESOURCEFILE          32789
#define ID_FILE_OPEN                    32790
#define ID_DEBUG_APP                    32791
#define ID_FILE_CLEAR                   32792
#define ID_FILE_EXPORT                  32793
#define ID_EXPORT_WAVEFRONTOBJ          32794
#define ID_DEBUG_GENERAL                32795
#define ID_OPTIONS_FPSLOCK              32796
#define ID_EXPORT_OGRE3D                32797
#define ID_IMPORT_AUTODESK3DS           32798
#define ID_IMPORT_MILKSHAPEMS3D         32799
#define ID_TOOLS_RESOURCEVIEWER         32800
#define ID_WINDOWS_TEXTURESDIALOG       32801
#define ID_WINDOWS_MODELDATA            32802
#define ID_OGRE3D_RELOADMESH            32803
#define ID_OGRE3D_RELOADRESOURCEFILE    32804
#define ID_TOOLS_OGREWIN3D              32805
#define ID_OPEN_LEVEL                   32806
#define ID_WINDOWS_FILEVIEW             32807
#define ID_WINDOWS_FPS                  32808
#define ID_WINDOWS_IMGUI                32809
#define ID_WINDOWS_PROPERTIES           32810
#define ID_OPEN_PROJECT                 32811
#define ID_FILE_EXPORT32812             32812
#define ID_FILE_SAVEPROJECTAS           32813
#define ID_FILE_SAVE                    32814
#define ID_Menu                         32815
#define ID_TOOLS_SOUNDPLAYER            32816
#define ID_FILE_NEW                     32817
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
