//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Room Builder.rc
//
#define IDC_MYICON                      2
#define IDD_ROOMBUILDER_DIALOG          102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_ROOMBUILDER                 107
#define IDI_SMALL                       108
#define IDC_ROOMBUILDER                 109
#define IDR_MAINFRAME                   128
#define IDD_BACK_SURFACE                129
#define IDD_MAP_TOP_LEFT                130
#define IDD_MAP_TOP_RIGHT               131
#define IDD_MAP_BOTTOM_LEFT             132
#define IDD_MAP_BOTTOM_RIGHT            133
#define IDD_MAPEDITOR                   134
#define IDD_MESSAGE                     135
#define IDD_SB_TABSDIALOG               136
#define IDD_PROPS_TEMPLATES             137
#define IDD_PROPS_BRUSHES               138
#define IDD_PROPS_TEXTURES              139
#define IDD_PLEASEWAIT                  140
#define IDD_SB_BRUSH_PROPERTIES         141
#define IDD_TOP_TABS_HEADERS            142
#define IDI_CUBE_PRIMITIVE              143
#define IDD_CREATE_BOX                  144
#define IDD_TEXT_DIALOG                 145
#define IDB_SOLIDBOX                    146
#define IDD_OGRE_EXPORT                 147
#define IDI_CYLINDER_PRIMITIVE          148
#define IDD_CREATE_CYLINDER             149
#define IDB_CYLINDERBIT                 151
#define IDD_YESNO_DLG                   152
#define IDI_CONE_PRIMITIVE              153
#define IDI_STAIRCASE_PRIMITIVE         154
#define IDI_ARCH_PRIMITIVE              155
#define IDI_SPHEROID_PRIMITIVE          156
#define IDD_TEXTURE_EDITOR              157
#define IDD_CREATE_CONE                 158
#define IDB_CREATECONE                  159
#define IDD_CREATE_STAIRCASE            160
#define IDB_CREATESTAIRS                161
#define IDB_CREATERAMP                  162
#define IDB_HOLLOWBOX                   163
#define IDD_BRUSH_DIMENSIONS            164
#define IDD_PROPS_FACES                 165
#define IDD_SNAPOPTIONS                 166
#define IDD_RESOURCE_VIEWER             167
#define IDD_TEXTUREVIEWER               168
#define IDD_TXL_EDITOR                  169
#define IDD_LISTDATA                    170
#define IDD_CREATE_ARCH                 171
#define IDD_OBJECT_EXPORT               172
#define IDD_MAP_RENDER_WINDOW           173
#define IDB_TR_ON                       174
#define IDB_BITMAP1                     175
#define IDB_TR_OFF                      175
#define IDD_LISTSCENE                   176
#define IDB_FILEINACTIVE                177
#define IDD_TOP_TABS_HEADERS_SCENE      177
#define IDB_TREE                        178
#define IDB_FILE                        179
#define IDB_FILESELECTED                180
#define IDB_FILECHANGED                 181
#define IDB_FILECHANGEDSELECTED         182
#define IDB_FVFOLDERRED                 183
#define IDR_SCENE_MENU                  184
#define IDC_BANNER                      1000
#define IDC_STTEXT                      1001
#define IDC_STMESSAGE                   1002
#define IDC_TBTEMPLATES                 1003
#define IDC_TBTEXTURES                  1004
#define IDC_TBGROUPS                    1005
#define IDC_BT_3DSETTINGS               1006
#define IDC_ED_PREVIEW                  1006
#define IDC_BTINSERT                    1007
#define IDC_ED_SCENE_EDITOR             1007
#define IDC_GD_BRUSHLIST                1008
#define IDC_ST_GD_GROUPS                1009
#define IDC_ST_GD_BRUSHCOUNT            1010
#define IDC_BRUSHCOUNT                  1011
#define IDC_STWAIT                      1012
#define IDC_LISTTDTEXTURES              1013
#define IDC_ST_GD_TEXTURES              1014
#define IDC_BASETEXTURE2                1015
#define IDC_STWIDTHHEIGHT               1016
#define IDC_BT_GD_BRUSHPROPERTIES       1017
#define IDC_BRUSH_PROPERTIESLIST        1018
#define IDC_ST_BP_SELECTEDBRUSHES       1019
#define IDC_CB_SELECTED_BRUSH           1020
#define IDC_BT_BRUSH_SELECT             1021
#define IDC_BT_BRUSH_MOVE               1022
#define IDC_BT_BRUSH_SCALE              1023
#define IDC_BT_BRUSH_SHEAR              1024
#define IDC_BT_BRUSH_DEBUG              1025
#define IDC_BT_BRUSH_ROTATE             1025
#define IDC_BRUSH_CUBE_PRIMITIVE        1026
#define IDC_BT_BOXSOLID                 1027
#define IDC_BT_BOXHOLLOW                1028
#define IDC_BT_BOXCUTBRUSH              1029
#define IDC_BOXDEFAULTS                 1030
#define IDC_BT_BOXROOM                  1031
#define IDC_XSIZETOP                    1032
#define IDC_ZSIZETOP                    1033
#define IDC_XSIZEBOT                    1034
#define IDC_ZSIZEBOT                    1035
#define IDC_YSIZE                       1036
#define IDC_THICKNESS                   1037
#define IDC_EDITNAME                    1038
#define IDC_CKWORLDCENTRE               1039
#define IDC_BT_BRUSH_RENAME             1040
#define IDC_CKCAMPOSITION               1040
#define IDC_EDITTEXT                    1041
#define IDC_TITLENAME                   1042
#define IDC_STTOP                       1043
#define IDC_STBOTTOM                    1044
#define IDC_STGENERAL                   1045
#define IDC_STTOPX                      1046
#define IDC_STZTOP                      1047
#define IDC_STBOTX                      1048
#define IDC_STBOTZ                      1049
#define IDC_STYSIZE                     1050
#define IDC_STWALL                      1051
#define IDC_STNAME                      1052
#define IDC_STCAMPOS                    1053
#define IDC_PICTURE                     1054
#define IDC_BTTDAPPLY                   1055
#define IDC_ST_OGRE_FILENAME            1056
#define IDC_ST_OGRE_PATH                1057
#define IDC_ST_STFILENAME               1058
#define IDC_ST_BANNER                   1059
#define IDC_ST_STPATH                   1060
#define IDC_BT_OGRE_NAMECHANGE          1061
#define IDC_BT_OGREBROWSE               1062
#define IDC_CK_BL_DESKTOP               1063
#define IDC_ST_OGRE_SUBFOLDER           1064
#define IDC_CK_CREATE_SUBDIR            1065
#define IDC_ST_STOGRESUB                1066
#define IDC_CK_BUILDEDGELIST            1067
#define IDC_BRUSH_CYCLINDER_PRIMITIVE   1068
#define IDC_TOPXSIZE                    1069
#define IDC_TOPZSIZE                    1070
#define IDC_TOPXOFF                     1071
#define IDC_TOPZOFF                     1072
#define IDC_BOTXSIZE                    1073
#define IDC_BOTZSIZE                    1074
#define IDC_BOTXOFF                     1075
#define IDC_BOTZOFF                     1076
#define IDC_VERTSTRIPES                 1078
#define IDC_RINGLENGTH                  1080
#define IDC_CYL_DEFAULTS                1081
#define IDC_CHECK2                      1084
#define IDC_TCUT                        1088
#define IDC_CYL_SOLID                   1089
#define IDC_CYL_HOLLOW                  1090
#define IDC_CYL_RING                    1091
#define IDC_STTOPXSIZE                  1092
#define IDC_BT_DELETE_SEL_BRUSH         1093
#define IDC_STTOPZSIZE                  1094
#define IDC_STTOPXOFFSET                1095
#define IDC_STTOPZOFFSET                1096
#define IDC_BRUSH_CONE_PRIMITIVE        1097
#define IDC_BRUSH_SPHEROID_PRIMITIVE    1098
#define IDC_BRUSH_STAIRCASE_PRIMITIVE   1099
#define IDC_TEXTURELIST2                1099
#define IDC_BRUSH_ARCH_PRIMITIVE        1100
#define IDC_PREVIEW                     1100
#define IDC_GEINFO                      1101
#define IDC_BT_ADD_TEXTURE              1103
#define IDC_BT_DELETE_TEXTURE           1104
#define IDC_BT_TXL_FILE_EDIT            1104
#define IDC_BT_TXL_RENAME               1105
#define IDC_STBOTXSIZE                  1106
#define IDC_STBOTZSIZE                  1107
#define IDC_STBOTXOFFSET                1108
#define IDC_STBOTZOFFSET                1109
#define IDC_BT_CUTBRUSH                 1110
#define IDC_BT_CYL_SOLID                1111
#define IDC_STWALLTHICKNESS             1112
#define IDC_STRINGLENGTH                1113
#define IDC_STSTRIPES                   1114
#define IDC_BT_CYL_HOLLOW               1115
#define IDC_BT_CYL_RING                 1116
#define IDC_ST_TEMPLATES                1117
#define IDC_BT_CONE_DEFAULTS            1118
#define IDC_ED_CONE_1                   1119
#define IDC_ED_CONE_2                   1120
#define IDC_ED_CONE_3                   1121
#define IDC_ED_CONE_4                   1122
#define IDC_ED_CONE_NAME                1123
#define IDC_CK_CONE_WORLDCENTRE         1124
#define IDC_CK_CONE_CAMPOSITION         1125
#define IDC_BT_CONE_SOLID               1126
#define IDC_BT_CONE_HOLLOW              1127
#define IDC_BT_CONE_FUNNEL              1128
#define IDC_BT_CONE_CUTBRUSH            1129
#define IDC_ST_CONE_NAME                1130
#define IDC_ST_CONE_POSITION            1131
#define IDC_STDIAMETER                  1132
#define IDC_STVERTSTRIPS                1133
#define IDC_STWALLSIZE                  1134
#define IDC_BT_NEXTFACE                 1135
#define IDC_BT_ALLFACES                 1136
#define IDC_BT_TEXTURE_FACE_PROPS       1136
#define IDC_BT_PREVFACE                 1137
#define IDC_ST_PIC                      1137
#define IDC_BT_STAIRS_DEFAULTS          1138
#define IDC_ED_STAIRS_HEIGHT            1139
#define IDC_ED_STAIRS_WIDTH             1140
#define IDC_ED_STAIRS_LENGTH            1141
#define IDC_ED_STAIRS_STEPS             1142
#define IDC_STAIRS_EDITNAME             1145
#define IDC_CK_STAIRS_WORLDCENTRE       1146
#define IDC_CK_STAIRS_CAMPOSITION       1147
#define IDC_ST_STAIRS_HEIGHT            1148
#define IDC_ST_STAIRS_WIDTH             1149
#define IDC_ST_STAIRS_LENGTH            1150
#define IDC_ST_STAIRS_STEPS             1151
#define IDC_ST_STAIRS_GENERAL           1152
#define IDC_ST_STAIRS_NAME              1153
#define IDC_ST_STAIRS_POSITION          1154
#define IDC_BT_STAIRS_STAIRS            1155
#define IDC_BT_STAIRS_RAMP              1156
#define IDC_BT_STAIRS_CUT               1157
#define IDC_BT_VLATEST                  1158
#define IDC_ST_VERSION                  1159
#define IDC_BT_VL18                     1160
#define IDC_ST_HEADER_FACES             1160
#define IDC_BT_VL17                     1161
#define IDC_ST_HEADER_BRUSHES           1161
#define IDC_BUTTON1                     1162
#define IDC_BT_TOP_LEFT                 1162
#define IDC_BT_ARCHSOLID                1162
#define IDC_BT_COPY_TEXTINFO            1162
#define IDC_BT_MAINENVIRONMENT          1162
#define IDC_BUTTON2                     1163
#define IDC_BT_BRUSH_DIMENSIONS         1163
#define IDC_BT_TOP_RIGHT                1163
#define IDC_BT_ARCHHOLLOW               1163
#define IDC_BT_PASTE_TEXTINFO           1163
#define IDC_BUTTON3                     1164
#define IDC_ED_BRUSH_POSX               1164
#define IDC_BT_BOTTOM_LEFT              1164
#define IDC_BT_ARCHRING                 1164
#define IDC_BUTTON4                     1165
#define IDC_ED_BRUSH_POSY               1165
#define IDC_BT_FULL_3D                  1165
#define IDC_BT_ARCHCUT                  1165
#define IDC_ED_BRUSH_POSZ               1166
#define IDC_ED_BRUSH_ROTX               1167
#define IDC_ED_BRUSH_ROTY               1168
#define IDC_ED_BRUSH_ROTZ               1169
#define IDC_ED_BRUSH_SCALEX             1170
#define IDC_ED_BRUSH_SCALEY             1171
#define IDC_ED_BRUSH_SCALEZ             1172
#define IDC_SBPOSXH                     1173
#define IDC_SBPOSYH                     1174
#define IDC_SBPOSZH                     1175
#define IDC_SBROTX                      1176
#define IDC_SBROTY                      1177
#define IDC_SBROTZ                      1178
#define IDC_SBSCALEX                    1179
#define IDC_SBSCALEY                    1180
#define IDC_SBSCALEZ                    1181
#define IDC_CBPOSXDELTA                 1182
#define IDC_CBPOSYDELTA                 1183
#define IDC_CBPOSZDELTA                 1184
#define IDC_CBROTXDELTA                 1185
#define IDC_CBROTYDELTA                 1186
#define IDC_CBROTZDELTA                 1187
#define IDC_COMBO7                      1188
#define IDC_STPOSX                      1189
#define IDC_COMBO8                      1190
#define IDC_COMBO9                      1191
#define IDC_STPOSY                      1192
#define IDC_STPOSZ                      1193
#define IDC_STROTX                      1194
#define IDC_STROTY                      1195
#define IDC_STROTZ                      1196
#define IDC_STSIZEX                     1197
#define IDC_STSIZEY                     1198
#define IDC_STSIZEZ                     1199
#define IDC_ST_DIM_POSITION             1200
#define IDC_ST_DIM_ROTATION             1201
#define IDC_ST_SELECTED                 1201
#define IDC_ST_DIM_SCALE                1202
#define IDC_ST_SELECTED_NUM             1202
#define IDC_LST_FACELIST                1203
#define IDC_LABEL_NUM_FACES             1204
#define IDC_ST_NUM_FACES                1205
#define IDC_ST_EDITXOFFSET              1206
#define IDC_ST_EDITYOFFSET              1207
#define IDC_ST_EDITXSCALE               1208
#define IDC_ST_EDITYSCALE               1209
#define IDC_ST_EDITANGLE                1210
#define IDC_SBXOFFSET                   1211
#define IDC_SBYOFFSET                   1212
#define IDC_CB_FACELIST                 1212
#define IDC_SBANGLE                     1213
#define IDC_BT_GL                       1213
#define IDC_SBXSCALE                    1214
#define IDC_SBXOFFSET3                  1215
#define IDC_SBYSCALE                    1215
#define IDC_STTEXTSCALE                 1216
#define IDC_STTEXTOFFSET                1217
#define IDC_ST_ANGLE                    1218
#define IDC_CBXOFFSET                   1219
#define IDC_CBYOFFSET                   1220
#define IDC_CBXSCALE                    1221
#define IDC_CBYSCALE                    1222
#define IDC_ST_X                        1223
#define IDC_ST_Y                        1224
#define IDC_FLIPHORIZONTAL              1225
#define IDC_FLIPVERTICAL                1226
#define IDC_CBANGLE                     1227
#define IDC_RADIO1                      1227
#define IDC_RADIO2                      1228
#define IDC_RADIO4                      1229
#define IDC_RADIO8                      1230
#define IDC_RADIO16                     1231
#define IDC_RADIO32                     1232
#define IDC_USESNAP                     1233
#define IDC_SNAP15                      1234
#define IDC_SNAP30                      1235
#define IDC_SNAP45                      1236
#define IDC_SNAP60                      1237
#define IDC_SNAP90                      1238
#define IDC_ST_GRIDSNAP                 1239
#define IDC_ST_ROTATIONSNAP             1240
#define IDC_EDIT1                       1241
#define IDC_ED_DEGREES                  1241
#define IDC_STARTANGLE                  1241
#define IDC_SPIN1                       1242
#define IDC_ENDANGLE                    1242
#define IDC_ST_DEGREES                  1243
#define IDC_LST_GROUPS                  1243
#define IDC_RADIUS                      1243
#define IDC_STCOUNT                     1244
#define IDC_WALLSIZE                    1244
#define IDC_ST_GB_OPTIONS               1245
#define IDC_NUMSLITS                    1245
#define IDC_BT_VIEWFILE                 1246
#define IDC_HEIGHT                      1246
#define IDC_ST_SELECTEDFILE             1247
#define IDC_BASETEXTURE                 1248
#define IDC_WIDTH                       1248
#define IDC_ST_GB_LISTOPTIONS           1249
#define IDC_RADIUS2                     1249
#define IDC_GROUPALL                    1250
#define IDC_EDIT10                      1250
#define IDC_SIDES                       1250
#define IDC_ALLMATERIALS                1251
#define IDC_EDIT11                      1251
#define IDC_ALLTEXTURES                 1252
#define IDC_ALLMESH                     1253
#define IDC_BT_LIST_OVERLAY             1254
#define IDC_BT_LIST_SKELETON            1255
#define IDC_ST_RESOURCE_GROUP           1256
#define IDC_ST_TEXTURE_NAME             1257
#define IDC_ST_FACEINFO                 1258
#define IDC_LIST1                       1259
#define IDC_LST_FACE_INFO               1259
#define IDC_LST_GENERAL                 1259
#define IDC_LIST_ABOUT_VERSIONS         1259
#define IDC_TXL_DELETE_TEXTURE          1260
#define IDC_ST_TXL_COUNT                1261
#define IDC_TXL_ADD_TEXTURE             1262
#define IDB_CREATEARCH                  1263
#define IDC_STSHAPE                     1264
#define IDC_STSTYLE                     1265
#define IDC_BT_ARCHRECTANGLE            1266
#define IDC_BT_ARCHROUND                1267
#define IDC_STSTARTANGLE                1268
#define IDC_STENDANGLE                  1269
#define IDC_STINNERRADIUS               1270
#define IDC_STNUMSEGS                   1271
#define IDC_STHEIGHT                    1272
#define IDC_STTHICKNESS                 1273
#define IDC_STWIDTH                     1274
#define IDC_STRADIUS                    1275
#define IDC_STSIDES                     1276
#define IDC_ST_ABOUT_BANNER             1277
#define IDC_ST_ABOUT_VERSION            1278
#define IDC_ST_TL_TITLE                 1280
#define IDC_ST_TR_TITLE                 1281
#define IDC_ST_BL_TITLE                 1282
#define IDC_CK_ALLFACES                 1283
#define IDC_ST_3D_TITLE                 1284
#define IDC_TREE1                       1285
#define IDC_BT_MAP_EDITOR               1286
#define ID_DEBUG_GENERAL                32771
#define ID_TEMPLATES_INSERT             32772
#define ID_BRUSH_SELECT                 32773
#define ID_BRUSH_MOVE                   32774
#define ID_BRUSH_SCALE                  32775
#define ID_BRUSH_SHEAR                  32776
#define ID_FACES_SELECTALLFACESINBRUSH  32777
#define ID_FILE_SAVE                    32778
#define ID_FILE_                        32779
#define ID_FILE_EXPORT                  32780
#define ID_FILE_SAVEAS                  32781
#define ID_EXPORT_OGRE3D                32782
#define ID_FILE_OPEN                    32783
#define ID_TOOLS_BRUSH_MOVEROTATEBRUSH  32784
#define ID_EDIT_SELECTALL               32784
#define ID_TOOLS_BRUSH_SCALEBRUSH       32785
#define ID_EDIT_DESELECTALL             32785
#define ID_FILE_OPENEXAMPLES            32786
#define ID_OPENEXAMPLES_TESTSCENE       32787
#define ID_CAMERA_TRACKCAMERA           32788
#define ID_CAMERA_RESETCAMERAZERO       32789
#define ID_TOOLS_TEXTURESEDITOR         32790
#define ID_DEBUG_SELECTIONSTATES        32791
#define ID_DEBUG_SHOWALLFACES3D         32792
#define ID_VIEW_PATHS                   32793
#define ID_DEBUG_RENDERSELECTEDFACE     32794
#define ID_WINDOW_PROPERTIES            32795
#define ID_OPENEXAMPLES_CUTBRUSHES      32796
#define ID_OPENEXAMPLES_TWOROOMS        32797
#define ID_VIEW_RESETVIEWS              32798
#define ID_GRID                         32799
#define ID_GRID_GRIDSNAP                32800
#define ID_GRID_SNAPOPTOPNS             32801
#define ID_TOOLS_RESOURCEVIEWER         32802
#define ID_TOOLS_TEXTURESEDITORNEW      32803
#define ID_TEXTURES_TEXTURESFILEEDITOR  32804
#define ID_TEXTURES_USEDTEXTURES        32805
#define ID_RENDER_TEXTURED              32806
#define ID_RENDER                       32807
#define ID_RENDER_TEXTURED32808         32808
#define ID_CAMERA_TEXTURED              32809
#define ID_CAMERA_WIREFRAMED            32810
#define ID_EXPORT_OBJECTWAVEFRONT       32811
#define ID_CAMERA_SPEED                 32812
#define ID_SPEED_NORMAL                 32813
#define ID_SPEED_SLOW                   32814
#define ID_SPEED_VERYSLOW               32815
#define ID_SPEED_FAST                   32816
#define ID_TEXTURES_LOCKALLTEXTURES     32817
#define ID_FILE_CLEAR                   32818
#define ID_GENERALSELECT                32886
#define ID_TOOLS_TEMPLATE               32910
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        185
#define _APS_NEXT_COMMAND_VALUE         32819
#define _APS_NEXT_CONTROL_VALUE         1287
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
