//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Room Builder.rc
//
#define IDC_MYICON                      2
#define IDD_ROOMBUILDER_DIALOG          102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_ROOMBUILDER                 107
#define IDI_SMALL                       108
#define IDC_ROOMBUILDER                 109
#define IDR_MAINFRAME                   128
#define IDD_BACK_SURFACE                129
#define IDD_MAP_TOP_LEFT                130
#define IDD_MAP_TOP_RIGHT               131
#define IDD_MAP_BOTTOM_LEFT             132
#define IDD_MAP_BOTTOM_RIGHT            133
#define IDD_MAPEDITOR                   134
#define IDD_MESSAGE                     135
#define IDD_SB_TABSDIALOG               136
#define IDD_PROPS_TEMPLATES             137
#define IDD_PROPS_BRUSHES               138
#define IDD_PROPS_TEXTURES              139
#define IDD_PLEASEWAIT                  140
#define IDD_SB_BRUSH_PROPERTIES         141
#define IDD_TOP_TABS_HEADERS            142
#define IDI_CUBE_PRIMITIVE              143
#define IDD_CREATE_BOX                  144
#define IDD_TEXT_DIALOG                 145
#define IDB_SOLIDBOX                    146
#define IDD_OGRE_EXPORT                 147
#define IDC_BANNER                      1000
#define IDC_STTEXT                      1001
#define IDC_STMESSAGE                   1002
#define IDC_TBTEMPLATES                 1003
#define IDC_TBTEXTURES                  1004
#define IDC_TBGROUPS                    1005
#define IDC_BT_3DSETTINGS               1006
#define IDC_BTINSERT                    1007
#define IDC_GD_BRUSHLIST                1008
#define IDC_ST_GD_GROUPS                1009
#define IDC_ST_GD_BRUSHCOUNT            1010
#define IDC_BRUSHCOUNT                  1011
#define IDC_STWAIT                      1012
#define IDC_LISTTDTEXTURES              1013
#define IDC_ST_GD_TEXTURES              1014
#define IDC_BASETEXTURE2                1015
#define IDC_STWIDTHHEIGHT               1016
#define IDC_BT_GD_BRUSHPROPERTIES       1017
#define IDC_BRUSH_PROPERTIESLIST        1018
#define IDC_ST_BP_SELECTEDBRUSHES       1019
#define IDC_CB_SELECTED_BRUSH           1020
#define IDC_BT_BRUSH_SELECT             1021
#define IDC_BT_BRUSH_MOVE               1022
#define IDC_BT_BRUSH_SCALE              1023
#define IDC_BT_BRUSH_SHEAR              1024
#define IDC_BT_BRUSH_DEBUG              1025
#define IDC_BRUSH_CUBE_PRIMITIVE        1026
#define IDC_BT_BOXSOLID                 1027
#define IDC_BT_BOXHOLLOW                1028
#define IDC_BT_BOXCUTBRUSH              1029
#define IDC_BOXDEFAULTS                 1030
#define IDC_BT_BOXROOM                  1031
#define IDC_XSIZETOP                    1032
#define IDC_ZSIZETOP                    1033
#define IDC_XSIZEBOT                    1034
#define IDC_ZSIZEBOT                    1035
#define IDC_YSIZE                       1036
#define IDC_THICKNESS                   1037
#define IDC_EDITNAME                    1038
#define IDC_CKWORLDCENTRE               1039
#define IDC_BT_BRUSH_RENAME             1040
#define IDC_CKCAMPOSITION               1040
#define IDC_EDITTEXT                    1041
#define IDC_TITLENAME                   1042
#define IDC_STTOP                       1043
#define IDC_STBOTTOM                    1044
#define IDC_STGENERAL                   1045
#define IDC_STTOPX                      1046
#define IDC_STZTOP                      1047
#define IDC_STBOTX                      1048
#define IDC_STBOTZ                      1049
#define IDC_STYSIZE                     1050
#define IDC_STWALL                      1051
#define IDC_STNAME                      1052
#define IDC_STCAMPOS                    1053
#define IDC_PICTURE                     1054
#define IDC_BTTDAPPLY                   1055
#define IDC_ST_OGRE_FILENAME            1056
#define IDC_ST_OGRE_PATH                1057
#define IDC_ST_STFILENAME               1058
#define IDC_ST_BANNER                   1059
#define IDC_ST_STPATH                   1060
#define IDC_BT_OGRE_NAMECHANGE          1061
#define IDC_BT_OGREBROWSE               1062
#define IDC_CK_BL_DESKTOP               1063
#define IDC_ST_OGRE_SUBFOLDER           1064
#define IDC_CK_CREATE_SUBDIR            1065
#define IDC_ST_STOGRESUB                1066
#define IDC_CK_BUILDEDGELIST            1067
#define ID_DEBUG_GENERAL                32771
#define ID_TEMPLATES_INSERT             32772
#define ID_BRUSH_SELECT                 32773
#define ID_BRUSH_MOVE                   32774
#define ID_BRUSH_SCALE                  32775
#define ID_BRUSH_SHEAR                  32776
#define ID_FACES_SELECTALLFACESINBRUSH  32777
#define ID_FILE_SAVE                    32778
#define ID_FILE_                        32779
#define ID_FILE_EXPORT                  32780
#define ID_FILE_SAVEAS                  32781
#define ID_EXPORT_OGRE3D                32782
#define ID_FILE_OPEN                    32783
#define ID_TOOLS_BRUSH_MOVEROTATEBRUSH  32784
#define ID_EDIT_SELECTALL               32784
#define ID_TOOLS_BRUSH_SCALEBRUSH       32785
#define ID_EDIT_DESELECTALL             32785
#define ID_GENERALSELECT                32886
#define ID_TOOLS_TEMPLATE               32910
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
