//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GD64.rc
//
#define IDC_MYICON                      2
#define IDD_GD64_DIALOG                 102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDS_VERSION                     104
#define IDM_EXIT                        105
#define IDI_GD64                        107
#define IDI_SMALL                       108
#define IDC_GD64                        109
#define IDR_MAINFRAME                   128
#define IDD_FILEVIEW                    129
#define IDD_VIEWER3D                    130
#define ID_VIEW_TOPVIEW                 131
#define ID_VIEW_SIDEVIEW                132
#define ID_VIEW_FRONTVIEW               133
#define IDD_PREFERENCES                 134
#define IDD_TOPBAR                      135
#define IDD_TB_TAB                      136
#define IDD_TB_DEBUG                    137
#define IDB_GRIDON                      138
#define IDD_TB_CAMERA                   138
#define IDB_GRIDOFF                     139
#define IDD_TB_CAMERA1                  139
#define IDD_TB_DEMOS                    139
#define IDB_HAIRON                      140
#define IDB_HAIROFF                     141
#define IDD_MESSAGE                     142
#define IDD_RESOURCESMATERIAL           143
#define IDD_IMPORT_OPTIONS              144
#define IDD_PLEASEWAIT                  145
#define IDB_MESHON                      146
#define IDB_MESHOFF                     147
#define IDB_TB_MODELDATAON              148
#define IDB_TB_MODELDATAOFF             149
#define IDB_BONDINGBOXON                150
#define IDB_BONDINGBOXOFF               151
#define IDB_MESHPOINTSON                152
#define IDB_MESHPOINTSOFF               153
#define IDB_BONESON                     154
#define IDB_BONESOFF                    155
#define IDB_NORMALSON                   156
#define IDB_NORMALSOFF                  157
#define IDB_TEXTURESON                  158
#define IDB_TEXTURESOFF                 159
#define IDB_BITMAP1                     160
#define IDB_DUMMY                       160
#define IDD_YESNO                       161
#define IDC_CK_SU_FULLSCREEN            1000
#define IDC_ST_STARTUP                  1001
#define IDC_CK_SU_FULL3DVIEW            1002
#define IDC_BT_TDH_DEBUG                1002
#define IDC_BT_TD_DEBUG_RESETVIEW       1003
#define IDC_BT_TD_DEBUG_IMGUIDEMO       1004
#define IDC_BT_TD_DEBUG_TESTCUBE        1005
#define IDC_BT_TD_DEBUG_IMGUIFPS        1006
#define IDC_BUTTON1                     1007
#define IDC_BT_APPRESOURCES             1007
#define IDC_BT_TD_DEBUG_TRAYSFPS        1007
#define IDC_BTSHOWTEXTURES              1007
#define IDC_BUTTON2                     1008
#define IDC_BT_TBH_CAMERA               1008
#define IDC_BT_DEMORESOURCES            1008
#define IDC_BTSHOWNORMALS               1008
#define IDC_BUTTON3                     1009
#define IDC_BT_CAMERA_MODEL             1009
#define IDC_ALLMESH                     1009
#define IDC_TBSHOWFACES                 1009
#define IDC_BUTTON4                     1010
#define IDC_BT_CAMERA_FREE              1010
#define IDC_ALLMATERIALS                1010
#define IDC_BTSHOWBONES                 1010
#define IDC_TBSHOWHAIR                  1011
#define IDC_BT_TD_DEBUG_PHYSICSDEBUG    1011
#define IDC_TBSHOWGRID                  1012
#define IDC_BT_TD_DEMOSTAB              1012
#define IDC_BT_TD_DEMOS_DEMO1           1013
#define IDC_BTSHOWPOINTS                1013
#define IDC_BT_TD_DEMOS_DEMO2           1014
#define IDC_TBBOUNDBOX                  1014
#define IDC_BANNER                      1015
#define IDC_BUTTON7                     1015
#define IDC_STTEXT                      1016
#define IDC_TBINFO                      1016
#define IDC_BT_TD_DEBUG_RESOURCES       1017
#define IDC_ST_BANNER                   1018
#define IDC_USEDMATERIALS               1019
#define IDC_ALLTEXTURES                 1020
#define IDC_ST_ABOUT_BANNER             1021
#define IDC_CK_COVERT_TO_OGRE           1022
#define IDC_CK_CREATEPHYSICS            1023
#define IDC_STWAIT                      1023
#define IDC_ST_ABOUT_VERSION            1024
#define IDC_LIST_ABOUT_VERSIONS         1025
#define IDC_STCOUNT                     1026
#define IDC_BANNER_YN                   1027
#define IDC_STTEXT_YN                   1028
#define ID_VIEW_RESET                   32771
#define ID_VIEW_MAX3DVIEW               32772
#define ID_DEBUG_TESTPREFERANCE         32773
#define ID_OPTIONS_PREFERENCES          32774
#define ID_FILE_IMPORT                  32775
#define ID_IMPORT_WAVEFRONTOBJ          32776
#define ID_DEBUG_HIDEOGRETESTCUBE       32777
#define ID_DEBUG_IMGUI                  32778
#define ID_IMGUI_IMGUIDEMO              32779
#define ID_CAMERA_MODE                  32780
#define ID_MODE_MODEL                   32781
#define ID_MODE_FREE                    32782
#define ID_DEBUG_CAMERADATA             32783
#define ID_INFO_ASSIMPMODELDATA         32784
#define ID_FILE_CONVERTTOOGRE3D         32785
#define ID_MOUSEANDKEYS                 32786
#define ID_IMPORT_OGRE3D                32787
#define ID_OGRE3D_MESH                  32788
#define ID_OGRE3D_RESOURCEFILE          32789
#define ID_FILE_OPEN                    32790
#define ID_DEBUG_APP                    32791
#define ID_FILE_CLEAR                   32792
#define ID_FILE_EXPORT                  32793
#define ID_EXPORT_WAVEFRONTOBJ          32794
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
